TrajectoryPlannerROS:

  holonomic_robot: false
  sim_time: 2.0
  meter_scoring: true
  max_vel_x: 0.4 
  min_vel_x: 0.1
  max_vel_theta: 0.7
  min_vel_theta: -0.7
  acc_lim_x: 0.6 
  acc_lim_y: 0.6 
  acc_lim_theta: 1.5 
