map_type: costmap

obstacle_range: 2.5
raytrace_range: 3.0
robot_radius: 0.11
inflation_radius: 0.15
transform_tolerance: 0.5
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /robokoko/laser/scan, marking: true, clearing: true}


